/**
 * @File Name          : RecursiveTriggerHandler.cls
 * @Description        : 
 * @Author             : Hassan Dakhcha
 * @Group              : 
 * @Last Modified By   : Hassan Dakhcha
 * @Last Modified On   : 5/20/2020, 12:16:39 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    5/20/2020   Hassan Dakhcha     Initial Version
**/
public class RecursiveTriggerHandler {
    public static Boolean isFirstTime = true;
}